version: '3'
services:
  sdc-service:
    image: geophray/sdc-service
    environment:
      - DB_HOST=ec2-100-25-180-4.compute-1.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=cartgames
      - DB_USER=cartgames
    ports:
      - "3001:3001"